name: tf-1.10
channels:
  - defaults
dependencies:
  - _tflow_1100_select=0.0.1=gpu
  - absl-py=0.4.0=py36h28b3542_0
  - astor=0.7.1=py36_0
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - cairo=1.14.12=h8948797_3
  - certifi=2018.8.24=py36_1
  - cudatoolkit=9.2=0
  - cudnn=7.2.1=cuda9.2_0
  - cupti=9.2.148=0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - gast=0.2.0=py36_0
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.12=h23475e2_2
  - graphviz=2.40.1=h21bd128_2
  - grpcio=1.12.1=py36hdbcaa40_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2018.0.3=0
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.34=hb9fc6fc_0
  - libprotobuf=3.6.0=hdbcaa40_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - markdown=2.6.11=py36_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.4=py36h4414c95_1
  - mkl_random=1.0.1=py36h4414c95_1
  - ncurses=6.1=hf484d3e_0
  - numpy=1.15.1=py36h1d66e8a_0
  - numpy-base=1.15.1=py36h81de0dd_0
  - openssl=1.0.2p=h14c3975_0
  - pango=1.42.4=h049681c_0
  - pcre=8.42=h439df22_0
  - pip=10.0.1=py36_0
  - pixman=0.34.0=hceecf20_3
  - protobuf=3.6.0=py36hf484d3e_0
  - pydot=1.2.4=py36_0
  - pyparsing=2.2.0=py36_1
  - python=3.6.6=hc3d631a_0
  - readline=7.0=h7b6447c_5
  - setuptools=40.2.0=py36_0
  - six=1.11.0=py36_1
  - sqlite=3.24.0=h84994c4_0
  - tensorboard=1.10.0=py36hf484d3e_0
  - tensorflow=1.10.0=gpu_py36hcebf108_0
  - tensorflow-base=1.10.0=gpu_py36had579c0_0
  - tensorflow-gpu=1.10.0=hf154084_0
  - termcolor=1.1.0=py36_1
  - tk=8.6.8=hbc83047_0
  - werkzeug=0.14.1=py36_0
  - wheel=0.31.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=ha838bed_2
prefix: /home/benjamintan/anaconda3/envs/tf-1.10
